config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :boats
  devise_for :users
  mount Sidekiq::Web => '/sidekiq' # monitoring console
  root 'boats#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
# frozen_string_literal: true

class Boat < ApplicationRecord
  validates :name,
            presence:   true,
            uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/boats_controller.rb
# frozen_string_literal: true

class BoatsController < ApplicationController
  before_action :set_boat, only: %i[show edit update destroy]

  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.all
  end

  # GET /boats/1
  # GET /boats/1.json
  def show; end

  # GET /boats/new
  def new
    @boat = Boat.new
  end

  # GET /boats/1/edit
  def edit; end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(boat_params)

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render :show, status: :created, location: @boat }
      else
        format.html { render :new }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update
    respond_to do |format|
      if @boat.update(boat_params)
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { render :show, status: :ok, location: @boat }
      else
        format.html { render :edit }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat.destroy
    respond_to do |format|
      format.html { redirect_to boats_url, notice: 'Boat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_boat
    @boat = Boat.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def boat_params
    params.require(:boat).permit(:name, :description)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Renders the home page.
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/boats_helper.rb
# frozen_string_literal: true

module BoatsHelper
end

app/helpers/layout_helper.rb
# frozen_string_literal: true

module LayoutHelper
  # Used to achieve nested layouts without content_for. This helper relies on
  # Rails internals, so beware that it make break with future major versions
  # of Rails. Inspired by http://stackoverflow.com/a/18214036
  #
  # Usage: For example, suppose "child" layout extends "parent" layout.
  # Use <%= yield %> as you would with non-nested layouts, as usual. Then on
  # the very last line of layouts/child.html.erb, include this:
  #
  #     <% parent_layout "parent" %>
  #
  # rubocop:disable Rails/HelperInstanceVariable
  def parent_layout(layout)
    @view_flow.set(:layout, output_buffer)
    output = render(template: "layouts/#{layout}")
    self.output_buffer = ActionView::OutputBuffer.new(output)
  end
  # rubocop:enable Rails/HelperInstanceVariable
end

app/helpers/navbar_helper.rb
# frozen_string_literal: true

module NavbarHelper
  # Generate <li><a href=...></a></li> appropriate for the Bootstrap navbar.
  # If :active_when hash is provided in the options, a class=active will
  # automatically be added to the <li> when appropriate.
  #
  # Example:
  #
  #     <%= navbar_link_to(
  #           "Home",
  #           root_path,
  #           active_when: { controller: "home" }) %>
  #
  def navbar_link_to(label, path, options={})
    active_when = options.delete(:active_when) { {} }
    active = active_when.all? do |key, value|
      case value
      when Regexp
        params[key].to_s =~ value
      else
        params[key].to_s == value
      end
    end

    content_tag(:li, class: ('active' if active)) do
      link_to(label, path, options)
    end
  end
end

app/helpers/retina_image_helper.rb
# frozen_string_literal: true

module RetinaImageHelper
  # Like the Rails image_tag, but adds a srcset attribute with an @2x version
  # of the image, thereby ensuring the image looks great on retina devices.
  # Assumes that the retina version of the image is named the same with "@2x"
  # before the extension, like "image@2x.png". For example:
  #
  #   <%= retina_image_tag("logo.png") %>
  #
  # Produces:
  #
  #   <img src="/assets/logo.png"
  #        srcset="/assets/logo.png 1x,/assets/logo@2x.png 2x">
  #
  # The srcset attribute is supported by modern desktop browsers and iOS 8+.
  def retina_image_tag(src, options={})
    src_1x = image_path(src)
    src_2x = image_path(src.sub(/^(.*)(\.[^\.]+)$/, '\1@2x\2'))
    srcset = "#{src_1x} 1x,#{src_2x} 2x"

    image_tag(src, options.reverse_merge(srcset: srcset, alt: ''))
  end
end

app/views/boats/_form.html.erb
<%= bootstrap_form_for(@boat) do |f| %>

  <%= f.alert_message "Please review the problems below:" %>

  <%= f.text_field :name %>
  <%= f.text_area :description, rows: 5 %>

  <%= f.primary %>
  <%= link_to "Back", boats_path, class: "btn btn-link" %>

<% end %>

app/views/boats/edit.html.erb
<% provide(:title, "Editing boat") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/boats/index.html.erb
<% provide(:title, "Listing boats") %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @boats.each do |boat| %>
      <tr>
        <td><%= boat.name %></td>
        <td><%= boat.description %></td>
        <td>
          <div class="btn-group">
            <%= link_to boat, class: "btn btn-xs btn-default" do %>
              <%= fa_icon("eye", text: "Show") %>
            <% end %>
            <%= link_to edit_boat_path(boat), class: "btn btn-xs btn-default" do %>
              <%= fa_icon("pencil", text: "Edit") %>
            <% end %>
            <%= link_to boat, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this boat?" } do %>
              <%= fa_icon("trash-o", text: "Destroy") %>
            <% end %>
          </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_boat_path, class: "btn btn-default" do %>
  <%= fa_icon("plus", text: "New Boat") %>
<% end %>

app/views/boats/new.html.erb
<% provide(:title, "New boat") %>

<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/boats/show.html.erb
<% provide(:title) do %>
  Boat #<%= @boat.id %>
<% end %>

<table class="table table-bordered">
  <tbody>
    <tr>
      <th class="col-sm-2">Name</th>
      <td><%= @boat.name %></td>
    </tr>
    <tr>
      <th class="col-sm-2">Description</th>
      <td><%= @boat.description %></td>
    </tr>
  </tbody>
</table>

<p>
  <%= link_to "Edit", edit_boat_path(@boat), class: "btn btn-primary" %>
  <%= link_to "Back", boats_path, class: "btn btn-link" %>
</p>

app/views/home/index.html.erb
<% provide(:title, "Home") %>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<%# The "application" layout is the default layout. It extends "base"  %>
<%# to include things like header, footer, and alerts that are common  %>
<%# to most (but not all) views.                                       %>

<%= render("shared/navbar") %>

<div class="container">

  <%= render("shared/flash") %>
  <%= render("shared/page_header") %>

  <%= yield %>

  <%= render("shared/footer") %>

</div>

<% parent_layout "base" %>

app/views/layouts/base.html.erb
<%# The "base" layout contains boilerplate common to *all* views. %>

<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= strip_tags(yield(:title)) + " – " if content_for?(:title) %>
      Boats
    </title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Boats <%= Rails.application.config.version %> (<%= l(Rails.application.config.version_time) %>) -->

    <%# CSS should go closest to the top of the document as possible. %>
    <%= stylesheet_link_tag("application",
                            media: "all",
                            "data-turbolinks-track" => "reload") %>

    <%# JavaScript must be in head for Turbolinks to work. %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

    <%= yield(:head) %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%# Specifies the default name of home screen bookmark in iOS %>
    <meta name="apple-mobile-web-app-title" content="Boats">
  </head>
  <body>

    <%= yield %>

  </body>
</html>

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice].present? %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<%# Alert %>
<% if flash[:alert].present? %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/shared/_footer.html.erb
<hr>

<footer>
  <p>© Boats <%= Time.zone.now.strftime("%Y") %></p>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Boats", root_path, class: "navbar-brand") %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to("List of boats", boats_path, class: "navbar-brand") %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to("Log in", new_user_session_path, class: "navbar-brand") %>
        </li>
        <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "navbar-brand" %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/shared/_page_header.erb
<div class="page-header">
  <% if content_for?(:title) %>
    <h1><%= content_for(:title) %></h1>
    <%= content_for(:page_subhead) %>
  <% end %>
</div>